### ISSUE TITLE
Instruments Usage Error : Specified target process is invalid:

### ISSUE THREAD

**Issue by JulesMoorhouse** [idStar/ui-automation-runner#4]
Hi,

I'm probably quite late to the party, but I pretty much have identical shell scripts to what your script produces, with the exception to the app path, which for me is a full qualified path with udid's in it.

My springboard app name has a space in it, which could be the problem, however I tried every combination I can think of, including escaping the name, which I have to do in my shell script.

I've also tried turning on debugging but it hasn't highlighted the issue.

I'm using xcode 6.4.

The error I'm getting is :-
Instruments Usage Error : Specified target process is invalid:

Thanks so much for this, it looks like it has great promise.

Have you any ideas that I could try?
Also have you tried this with xcode 6.4?

**Comment by Jules2010** [comment]
Ahh I was trying  "iPhone 5s (7.1 Simulator)" which didn't complain, but which reported the app name was incorrect. However, the find command, was using this for the path (instead of the UDID which I wasn't supplying.

When I tried "iPhone 6 (8.1 Simulator)" it worked.

I know I've had problem with paths between iOS7 and iOS8, so I guess the simulator path must be incorrect in the runner shell script.

**Comment by idStar** [comment]
@Jules2010 Correct, you do have to be careful to modify the Simulators path as Xcode changes. I haven't run this script on any Xcode since version 6.0.1. At that time:

```
BASE_SIMULATORS_PATH="$HOME/Library/Developer/CoreSimulator/Devices"
```

Was the right path. However, if you just changed the name of which simulator you wanted to run, and that worked, then the _base_ path set above in the main script, is actually still valid.
